export const START_FETCH_WEATHER = 'START_FETCH_WEATHER'
export const SUCCESS_FETCH_WEATHER = 'SUCCESS_FETCH_WEATHER'
export const ERROR_FETCH_WEATHER = 'ERROR_FETCH_WEATHER'
export const CLEAR_WEATHER = 'CLEAR_WEATHER'