export const START_FETCH_PROFILE_USER = 'START_FETCH_PROFILE_USER'
export const SUCCESS_FETCH_PROFILE_USER = 'SUCCESS_FETCH_PROFILE_USER'
export const ERROR_FETCH_PROFILE_USER = 'START_FETCH_PROFILE_USER'